### ISSUE TITLE
Script fails with -H

### ISSUE THREAD

**Issue by fftux** [evgeni/katello-attach-subscription#18]
Script appears to run fine without the -H option.  As soon as the -H is introduced the script immediately bails.  There is not output even with -d.

I have manually verified the hypervisors in my lab are reporting virtual guests on the content host entry for the host (hosts -> content hosts -> <hypervisor> -> Virtual Guests).

**Comment by evgeni** [comment]
Hey @chopskxw!

`-H` just does a search for `virtual_guests:*`, which for some reason seem to fail (or at least not return any results) for you. I must admit I probably never tried this since Satellite 6.1 *cough*.

Let's see if I can find anything useful.

**Comment by fftux** [comment]
Thanks for taking a look.

**Comment by Rocco83** [comment]
A possibile solution is to make use of type, https://github.com/RedHatSatellite/katello-attach-subscription/issues/17, which still is not working in Satellite > 6.1.
Otherwise, the best solution would be to remove the option.

**Comment by evgeni** [comment]
fixed in 3821d6a4c03271b989b9bae9d745becab137aecb
