### ISSUE TITLE
Use virt-who --print for getting Hypervisors data instead of Satellite

### ISSUE THREAD

**Issue by mossicrue** [evgeni/katello-attach-subscription#20]
If custom facts of an hypervisor aren't available from Satellite, eg: hypervisors socket data are reported by virt-who but are stored only in candlepin DB and not stored in foreman DB / Satellite DB ([BZ1638814](https://bugzilla.redhat.com/show_bug.cgi?id=1638814)), we can call `virt-who --print` to retrieve custom facts that aren't present via API.

`virt-who --print` returns a json containing an array of hypervisor dictionary which has in `facts` sub-dictionary the data we are looking for.

```json
"facts": {
  "hypervisor.type": "VMware ESXi",
  "cpu.cpu_socket(s)": "4",
  "hypervisor.cluster": "cluster_name",
  "hypervisor.version": "6.5.0"
}
```

We can use `cpu.cpu_socket(s)` field to retrieve the number of sockets of an hypervisor and use this value as workaround of the solution I provided on issue #5.

**Comment by evgeni** [comment]
fixed in 3821d6a4c03271b989b9bae9d745becab137aecb
