### ISSUE TITLE
Permission table for running KAS without Satellite Admin User

### ISSUE THREAD

**Issue by mossicrue** [evgeni/katello-attach-subscription#21]
Add the permission table in the readme file with the correct grant to assign to a Satellite custom user for running katello-attach-subscription script without using a Satellite Admin User.

The correct permission are:

Resource | Permissions
------------ | -------------
Fact value | view_facts
Host | view_hosts, edit_hosts
Subscription | view_subscriptions, attach_subscriptions, unattach_subscriptions

**Comment by evgeni** [comment]
fixed in 3821d6a4c03271b989b9bae9d745becab137aecb
