### ISSUE TITLE
Option for check "density" of a cluster before attaching subscription

### ISSUE THREAD

**Issue by mossicrue** [evgeni/katello-attach-subscription#22]
Check that every hosts in a cluster has an average number of guests or more present and attach VDC Subscription to all the hypervisor present on it.

Cluster data reporting would be available in Satellite if using latest upstream version of [virt-who](https://github.com/candlepin/virt-who), if they aren't present we could use the cluster values in the json output of `virt-who --print` as a workaround, as suggested in issue #20.

**Comment by evgeni** [comment]
fixed in 3821d6a4c03271b989b9bae9d745becab137aecb
