### ISSUE TITLE
Clarify the "submitter" option

### ISSUE THREAD

**Issue by Rocco83** [evgeni/katello-attach-subscription#3]
Hi evgeni,

I am trying to understand how to use it.

In https://github.com/evgeni/katello-attach-subscription/blob/master/README.md#L12
You wrote
`Search for a subscription that matches by hostname and (optionally) by the submitter`

What a "submitter" really is? The "Registered by" field of one content host?

Thanks,
Daniele

**Comment by evgeni** [comment]
Yes, "registered by".

In case of virt-who it will be the UUID of the machine running virt-who.

If you can think of a better wording, be my patcher :)
