### ISSUE TITLE
calculating correct amount of subscriptions

### ISSUE THREAD

**Issue by Rocco83** [evgeni/katello-attach-subscription#5]
currently there is an explicitly set qty=1 in https://github.com/RedHatSatellite/katello-attach-subscription/blob/master/katello-attach-subscription#L134

It would be better to calculate, checking the socket number in system API, the correct amount of subscription to be attached.

When we call
https://satellite/katello/api/subscriptions/subscription_id_number
There is inside:

```
[...]
"available": 31,
"quantity": 39,
"consumed": 8,
[...]
"virt_only": false, 
"sockets": 2,
"cores": 0,
"ram": 0,
[...]
```

There is also "provided products", an hash of products that this key provide.
In a furter development, based on an hash of functionalities to be activated, we can also skip the subscription id.

In the output, follow also the systems entitled.

With this information we should be able to do the math in order to assign the subscriptions.

PR will follow.

**Comment by Rocco83** [comment]
The method to fix this issue may be:
0) check if one sub is needed for each "product" (rhel, scl, ...) and create an array of possible subscriptions for each product
1) check how many core that the system has - this is common to all "products"
for each product:
a) check how many cores every sub cover
b) select the best sub according to an algorithm:
if (core of sub > core of system ) skip to next.

Possible improvements:
- select in the list the sub that fit more than other (8 core for 8 core, 4 core for 4 core, ...)
- have the subs ordered by cores, so we can avoid some iteration.

Any comment on this?

**Comment by Rocco83** [comment]
@CalvinHartwell the PR #7 do not fix your problem, but i am working on it and put some common concept to be used.
If you wish to work on the patch, very welcome. i am working on it but i do not have too much time.

**Comment by mossicrue** [comment]
The solution to the problem could be use the value of `cpu::cpu_socket(s)` fields of `facts` dictionary present in Hosts API of Satellite (>= 6.3) and divide it with the `sockets` field present in the subscription API
e.g. the JSON response from calling https://satellite6.example.com/api/v2/hosts/:host_id?fields=full contain "cpu::cpu_socket(s)" field in "facts" sub-dictionary

```
"facts": {
"""
  "cpu::cpu(s)": "4",
  "cpu::core(s)_per_socket": "4",
  "cpu::cpu_socket(s)": "1",
  "cpu::thread(s)_per_core": "1",
"""
}
```

while calling https://satellite6.example.com/katello/api/organizations/:org_id/subscriptions/:sub_id return this value

```
{
"""
  "sockets": "2"
"""
}
```

So the correct number to add is the value that we obtaining doing `{ host cpu::cpu_socket(s) } / { subscription sockets }`
If host is partially entitled we have to remove the number of attached sub from the number obtained before.
**WARNING**: Currently there is a BUG with add_subscriptions API that not add but set the value passed so as workaround skip the 'remove number of attached sub' phase.
