### ISSUE TITLE
The script is too slow

### ISSUE THREAD

**Issue by Rocco83** [evgeni/katello-attach-subscription#6]
Hi,

the systems are too slow to be retrieved.
my suggestion is to use a cache file as support.

any comment?

**Comment by evgeni** [comment]
FWIW, I've added options to either look for hypervisors that actually have VMs running (according to Satellite/virt-who) or to have a search executed to limit the number of hosts to check. Both improve speed, but your point is still valid :)

**Comment by evgeni** [comment]
closed via 06a27a8897c60d1fe92e252137a2274ba34da817
